In [1]:
#matrix multiplication
import numpy as np
arr1=np.array((4,5,7,8,0,2,1,7,9)).reshape(3,3)
print("matrix 1: \n",arr1,"\n")
arr2=np.array((2,4,5,8,0,2,4,7,9)).reshape(3,3)
print("matrix 2: \n",arr2,"\n")

mul=np.dot(arr1,arr2)
print("Dot Product:\n\n",mul)


transpose=mul.transpose()
print("\n\nTranspose :\n\n",transpose)


matrix 1: 
 [[4 5 7]
 [8 0 2]
 [1 7 9]] 

matrix 2: 
 [[2 4 5]
 [8 0 2]
 [4 7 9]] 

Dot Product:

 [[ 76  65  93]
 [ 24  46  58]
 [ 94  67 100]]


Transpose :

 [[ 76  24  94]
 [ 65  46  67]
 [ 93  58 100]]
