In [1]:
#svd
import numpy as np
from scipy.linalg import svd

arr1=np.array((4,5,7,8,0,2,1,7,9)).reshape(3,3)
a,b,c=svd(arr1)
print("decomposed arrays:\n")
print(a)
print("\n\n",b)
print("\n\n",c)

print("Reconstructed array:\n")

e=(a @ np.diag(b) @ c)
new_arr=e.astype('i')
print("\n\n",new_arr)


decomposed arrays:

[[-0.6248785  -0.07107342 -0.77748018]
 [-0.29405228 -0.90108687  0.31870945]
 [-0.72322895  0.4277745   0.54217051]]


 [ 15.15586921   7.69969063   0.11997035]


 [[-0.36785493 -0.54018645 -0.75688926]
 [-0.91759714  0.34274811  0.20134352]
 [-0.15065932 -0.76858463  0.62175512]]
Reconstructed array:



 [[4 4 6]
 [8 0 1]
 [0 6 9]]
